services:
  mysql:
    image: mysql:8.0.33
    ports:
      - 13306:3306
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: seungkyu
      MYSQL_DATABASE: seungkyu